---
# handlers file for apache2-v2

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
