version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php-app
    restart: always

  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php:latest
    volumes:
      - ./php:/var/www/html
    expose:
      - "9000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: postgres:latest
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      retries: 5
      start_period: 10s
