apiVersion: v1
kind: Service
metadata:
  name: pod-using-pvc-service
  namespace: ns01
spec:
  selector:
    app: pod-using-pvc
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30305